app/users/forms.py
# -*- coding: utf-8 -*-

from flask_wtf import Form
from flask_babel import gettext
from flask_login import current_user

from wtforms import BooleanField, StringField, PasswordField
from wtforms.validators import Required, EqualTo, Email, Optional, Length
from werkzeug import check_password_hash, generate_password_hash
from app.users.models import User
import re # for checking username

def validate_username_characters(username):
    """Validates username"""
    return username == re.sub("[^a-zA-Z0-9_\.]", "", username)

def validate_username_blocked(username):
    """Checks if username is not blocked"""
    blocked_names = ['admin', 'mod', 'moderator']
    for blocked_name in blocked_names:
        # check if username is substring of blocked name
        if (username.lower() in blocked_name) or (blocked_name in username.lower()):
            return False

    return True

class RequiredIf(Required):
    # a validator which makes a field required if
    # another field is set and has a truthy value

    def __init__(self, other_field_name, *args, **kwargs):
        self.other_field_name = other_field_name
        super(RequiredIf, self).__init__(*args, **kwargs)

    def __call__(self, form, field):
        other_field = form._fields.get(self.other_field_name)
        if other_field is None:
            raise Exception('No field named "%s" in form' % self.other_field_name)

        if bool(other_field.data):
            super(RequiredIf, self).__call__(form, field)

class LoginForm(Form):
    email = StringField('Email Address', [Email(), Length(min=6, max=35)])
    password = PasswordField('Password', [Required()])
    remember_me = BooleanField('Remember me', [])

    # def validate(self):
    #     if not Form.validate(self):
    #         return False
    #
    #     # check username and password
    #     user = User.query.filter_by(username=self.username.data).first()
    #     if (user is None) or (not check_password_hash(user.password, self.password.data)):
    #         self.username.errors.append(u'Nie prawidłowe hasło lub nazwa użytkownika')
    #         return False

class RegisterForm(Form):
    username = StringField('Username', [Length(min=4, max=25)])
    email = StringField('Email Address', [Email(), Length(min=6, max=35)])
    password = PasswordField('Password', [Required()])
    confirm = PasswordField(
        'Repeat Password', [
            Required(),
            EqualTo('password', message=gettext(u'Passwords must match.'))
        ]
    )

    def validate(self):
        if not Form.validate(self):
            return False

        # check if username has valid characters
        if not validate_username_characters(self.username.data):
            self.username.errors.append(gettext(u'Username contains illegal characters.'))
            return False

        if not validate_username_blocked(self.username.data):
            self.username.errors.append(gettext(u'Username is blocked.'))
            return False

        # check username
        user = User.query.filter_by(username=self.username.data).first()
        if user is not None:
            self.username.errors.append(gettext(u'Username is already in use.'))
            return False

        # email check
        user = User.query.filter_by(email=self.email.data.lower()).first()
        if user is not None:
            self.email.errors.append(gettext(u'Email is already in use.'))
            return False

        return True

class AccountForm(Form):
    username = StringField('Username', [Length(min=4, max=25)])
    email = StringField('Email Address', [Email(), Length(min=6, max=35)])
    password = PasswordField('Password', [Optional()])
    confirm = PasswordField(
        'Repeat Password', [
            Optional(),
            EqualTo('password', message=gettext(u'Passwords must match.'))
        ]
    )
    old_password = PasswordField('Old Password', [RequiredIf('password')])

    def validate(self):
        if not Form.validate(self):
            return False

        # check if username has valid characters
        if not validate_username_characters(self.username.data):
            self.username.errors.append(gettext(u'Username contains illegal characters.'))
            return False

        if not validate_username_blocked(self.username.data):
            self.username.errors.append(gettext(u'Username is blocked.'))
            return False

        # check username
        user = User.query.filter_by(username=self.username.data).first()
        if (user is not None) and (user.id != current_user.id):
            self.username.errors.append(gettext(u'Username is already in use.'))
            return False

        # email check
        user = User.query.filter_by(email=self.email.data.lower()).first()
        if (user is not None) and (user.id != current_user.id):
            self.email.errors.append(gettext(u'Email is already in use.'))
            return False

        # check old password
        if ((self.old_password.data is not None) and self.old_password.data
                and (not check_password_hash(current_user.password, self.old_password.data))):
            self.old_password.errors.append(gettext(u'Old password is not correct.'))
            return False

        return True

class LostForm(Form):
    email = StringField('Email Address', [Email(), Length(min=6, max=35)])

    def validate(self):
        if not Form.validate(self):
            return False

        # email check
        user = User.query.filter_by(email=self.email.data.lower()).first()
        if user is None:
            self.email.errors.append(gettext(u'Email is not correct.'))
            return False

        if not user.confirmed:
            self.email.errors.append(gettext(u'User with this email is not confirmed.'))
            return False

        return True

class ChangePasswordForm(Form):
    password = PasswordField('Password', [Required()])
    confirm = PasswordField(
        'Repeat Password', [
            Required(),
            EqualTo('password', message=gettext(u'Passwords must match.'))
        ]
    )

app/users/views.py
# -*- coding: utf-8 -*-

from datetime import datetime
from werkzeug import check_password_hash, generate_password_hash
from flask import Blueprint, request, render_template, flash, redirect, url_for
from flask_login import current_user, login_user, logout_user, login_required
from flask_sqlalchemy import get_debug_queries
from flask_babel import gettext

from app import app, db
from app.users.models import User
from app.users.forms import RegisterForm, LoginForm, AccountForm, LostForm, ChangePasswordForm

from app.miscellaneous import not_login_required
from app.token import generate_confirmation_token, confirm_token, generate_lost_password_token
from app.email import send_email

from app.oauth import OAuthSignIn

mod = Blueprint('users', __name__, url_prefix='/users')

# check for slow quieries
@mod.after_request
def after_request(response):
    for query in get_debug_queries():
        if query.duration >= app.config['DATABASE_QUERY_TIMEOUT']:
            app.logger.warning(
                "SLOW QUERY: %s\nParameters: %s\nDuration: %fs\nContext: %s\n" %
                (query.statement, query.parameters, query.duration, query.context)
            )
    return response

# Login
@mod.route('/login/', methods=['GET', 'POST'])
@not_login_required
def login():
    """Handels user login"""

    # get form
    form = LoginForm(request.form)

    if request.method == 'GET':
        return render_template('users/login.html', form=form)

    # verify the login form
    if form.validate_on_submit():
        registered_user = User.query.filter_by(email=form.email.data).first()

        if ((registered_user is not None)
                and check_password_hash(registered_user.password, form.password.data)):
            # login user to system
            login_user(registered_user, remember=form.remember_me.data)
            registered_user.update_login_info()

            return redirect(request.args.get('next') or url_for('simple_page.index'))

        flash(gettext(u'Incorrect email or password'), 'danger')

    return render_template('users/login.html', form=form)

# Register
@mod.route('/register/', methods=['GET', 'POST'])
@not_login_required
def register():
    """Provides registering for user"""

    # if register form is submitted
    form = RegisterForm(request.form)

    # verify the register form
    if form.validate_on_submit():
        # create user and add to database
        user = User(
            username=form.username.data,
            password=generate_password_hash(form.password.data),
            email=form.email.data
        )
        db.session.add(user)
        db.session.commit()

        # sending email
        token = generate_confirmation_token(user.email)
        confirm_url = url_for('users.confirm_email', token=token, _external=True)
        html = render_template('users/activate.html', confirm_url=confirm_url)
        subject = gettext(u"Please confirm your email")
        send_email(user.email, subject, html)

        #login_user(user)

        # everything okay so far
        flash(gettext(u'Confirmation email has been sent'), 'info')
        return redirect(url_for('users.login'))

    return render_template('users/register.html', form=form)

# Logout
@mod.route('/logout/')
@login_required
def logout():
    """Logout user from the system"""

    # logout user from system
    logout_user()

    # everything okay so back
    return redirect(url_for('simple_page.index'))

# Account
@mod.route('/account/', methods=['GET', 'POST'])
@login_required
def account():
    """Show users informations"""

    # get form
    form = AccountForm(request.form, obj=current_user)

    # verify the register form
    if form.validate_on_submit():
        new_email = str(form.email.data)

        if str(current_user.email) != new_email:
            # reset confirmation status
            current_user.confirmed = False
            current_user.confirmed_on = None

            # resending email
            token = generate_confirmation_token(new_email)
            confirm_url = url_for('users.confirm_email', token=token, _external=True)
            html = render_template('users/activate.html', confirm_url=confirm_url)
            subject = gettext(u'Confirm your account - Adventure')
            send_email(new_email, subject, html)
            flash(gettext(u'Confirmation email has been sent'), 'info')

        # if password has not changed we set it to previous
        if ((form.password.data is None) or (not form.password.data)):
            form.password.data = current_user.password
        else: # generate normal password
            form.password.data = generate_password_hash(form.password.data)

        # update user
        form.populate_obj(current_user)

        # update user in database
        db.session.commit()

        # everything is okay
        flash(gettext(u'The changes have been saved'), 'success')
        return redirect(url_for('users.account'))

    return render_template('users/account.html', form=form)

# Lost password
@mod.route('/lost/', methods=['GET', 'POST'])
@not_login_required
def lost():
    """Allow for user to get lost password"""

    # get form
    form = LostForm(request.form)

    # verify the register form
    if form.validate_on_submit():
        token = generate_lost_password_token(form.email.data)
        confirm_url = url_for('users.change_password', token=token, _external=True)
        html = render_template('users/lost_email.html', confirm_url=confirm_url)
        subject = gettext(u'New password request - Adventure')
        send_email(form.email.data, subject, html)
        flash(gettext(u'Follow the instructions in sent email'), 'info')

        return redirect(url_for('simple_page.index'))

    return render_template('users/lost.html', form=form)

# Login authorization
@mod.route('/authorize/<provider>')
def oauth_authorize(provider):
    if not current_user.is_anonymous():
        return redirect(url_for('simple_page.index'))

    oauth = OAuthSignIn.get_provider(provider)
    return oauth.authorize()

# Sign in callback
@mod.route('/callback/<provider>')
def oauth_callback(provider):
    if not current_user.is_anonymous():
        return redirect(url_for('simple_page.index'))

    oauth = OAuthSignIn.get_provider(provider)
    social_id, username, email = oauth.callback()
    if social_id is None:
        flash(getttext(u'Authentication failed'), 'danger')
        return redirect(url_for('simple_page.index'))

    # check if user exists and if no creates new
    user = User.query.filter_by(social_id=social_id).first()
    if user is None:
        user = User(
            username=username,
            password='',
            email=email,
            social_id=social_id
        )
        db.session.add(user)
        db.session.commit()

    login_user(user, remember=True)
    user.update_login_info()
    return redirect(url_for('simple_page.index'))

# Send confirmation email
@mod.route('/confirmation/')
@login_required
def resend_confirmation_email():
    # resending email
    token = generate_confirmation_token(current_user.email)
    confirm_url = url_for('users.confirm_email', token=token, _external=True)
    html = render_template('users/activate.html', confirm_url=confirm_url)
    subject = gettext(u'Please confirm your email')
    send_email(current_user.email, subject, html)

    flash(gettext(u'Confirmation email has been sent'), 'info')
    return redirect(url_for('users.account'))

# Confirm email
@mod.route('/confirm/<token>', methods=['GET', 'POST'])
@login_required
def confirm_email(token):
    try:
        email = confirm_token(token)
    except:
        flash(gettext(u'The confirmation link is invalid or has expired'), 'warning')

    # check if user with decoded email exists
    user = User.query.filter_by(email=email).first_or_404()
    if user.confirmed:
        flash(gettext(u'Account already confirmed'), 'info')
        return redirect(url_for('simple_page.index'))

    # update user informations and add to database
    user.confirmed = True
    user.confirmed_on = datetime.now()
    db.session.add(user)
    db.session.commit()

    flash(gettext(u'You have confirmed your account. Enjoy'), 'success')
    return redirect(url_for('simple_page.index'))

# Change lost password
@mod.route('/lost/<token>', methods=['GET', 'POST'])
def change_password(token):
    try:
        email = confirm_token(token)
    except:
        flash(gettext(u'The confirmation link is invalid or has expired'), 'warning')

    # check if user with decoded email exists
    user = User.query.filter_by(email=email).first_or_404()

    form = ChangePasswordForm(request.form, obj=user)

    if form.validate_on_submit():
        # update user
        form.password.data = generate_password_hash(form.password.data)
        form.populate_obj(user)

        # update user in database
        db.session.commit()

        # everything is okay
        flash(gettext(u'Your password has been successfully changed'), 'success')
        return redirect(url_for('users.login'))

    return render_template('users/change_password.html', form=form)

app/templates/users/account.html
{% extends "layout.html" %}
{% block body %}
	{% macro render_field(field, placeholder=None) %}
		{% if field.errors %}
		<div>
		{% elif field.flags.error %}
		<div>
		{% else %}
		<div>
		{% endif %}

		{% set css_class = 'form-control ' + kwargs.pop('class', '') %}
		{{ field(class=css_class, placeholder=placeholder, **kwargs) }}
		</div>
	{% endmacro %}

	{% if not g.user.confirmed %}
		<div class="alert alert-warning" role="alert">
			{{ _('Your account has not been activated yet.') }}
			<a href="{{ url_for('users.resend_confirmation_email') }}">{{ _('Click here') }}</a> {{ _('to resend confirmation email.') }}
		</div>
		<br>
	{% endif %}

	<h2>{{ _('My account') }}</h2>
	<br><br>
	<form action="" method="post" name="register">
		{{ form.hidden_tag() }}

		<div class="form-group">
			<div class="input-group">
				<div class="input-group-addon"><i class="fa fa-user"></i></div>
				{{ render_field(form.username, placeholder=_('Username'), autofocus="") }}
			</div>
			<div class="form-group has-error">
				<small class="form-group has-error help-block">{{ form.username.errors[0] }}</small>
			</div>
		</div>

		<div class="form-group">
			<div class="input-group">
				<div class="input-group-addon"><i class="fa fa-envelope"></i></div>
				{{ render_field(form.email, placeholder=_('Email')) }}
			</div>
			<div class="form-group has-error">
				<small class="form-group has-error help-block">{{ form.email.errors[0] }}</small>
			</div>
		</div>

		<div class="form-group">
			<div class="input-group">
				<div class="input-group-addon"><i class="fa fa-lock"></i></div>
				{{ render_field(form.password, placeholder=_('Password')) }}
			</div>
			<div class="form-group has-error">
				<small class="form-group has-error help-block">{{ form.password.errors[0] }}</small>
			</div>
		</div>

		<div class="form-group">
			<div class="input-group">
				<div class="input-group-addon"><i class="fa fa-lock"></i></div>
				{{ render_field(form.confirm, placeholder=_('Repeat password')) }}
			</div>
			<div class="form-group has-error">
				<small class="form-group has-error help-block">{{ form.confirm.errors[0] }}</small>
			</div>
		</div>

		<div class="form-group">
			<div class="input-group">
				<div class="input-group-addon"><i class="fa fa-lock"></i></div>
				{{ render_field(form.old_password, placeholder=_('Old password')) }}
			</div>
			<div class="form-group has-error">
				<small class="form-group has-error help-block">{{ form.old_password.errors[0] }}</small>
			</div>
		</div>

		<div class="form-group">
			<button type="submit" class="btn btn-success">{{ _('Save changes') }}</button>
		</div>
	</form>
{% endblock %}

app/templates/users/activate.html
<p>Witaj w Przygodach! Thanks for signing up. Please follow this link to activate your account:</p>
<p><a href="{{ confirm_url|safe }}">{{ confirm_url|safe }}</a></p>
<br>
<p>Cheers!</p>

app/templates/users/change_password.html
{% extends "layout.html" %}
{% block body %}
	{% macro render_field(field, placeholder=None) %}
		{% if field.errors %}
		<div>
		{% elif field.flags.error %}
		<div>
		{% else %}
		<div>
		{% endif %}

		{% set css_class = 'form-control ' + kwargs.pop('class', '') %}
		{{ field(class=css_class, placeholder=placeholder, **kwargs) }}
		</div>
	{% endmacro %}

	<h2>{{ _('Reset password') }}</h2><br>

	<form action="" method="post" name="register">
		{{ form.hidden_tag() }}

		<div class="form-group">
			<div class="input-group">
				<div class="input-group-addon"><i class="fa fa-lock"></i></div>
				{{ render_field(form.password, placeholder=_('New password')) }}
			</div>
			<div class="form-group has-error">
				<small class="form-group has-error help-block">{{ form.password.errors[0] }}</small>
			</div>
		</div>

		<div class="form-group">
			<div class="input-group">
				<div class="input-group-addon"><i class="fa fa-lock"></i></div>
				{{ render_field(form.confirm, placeholder=_('Repeat password')) }}
			</div>
			<div class="form-group has-error">
				<small class="form-group has-error help-block">{{ form.confirm.errors[0] }}</small>
			</div>
		</div>

		<div class="form-group">
			<button type="submit" class="btn btn-success">{{ _('Reset your password') }}</button>
		</div>
	</form>
{% endblock %}

app/templates/users/login.html
<!-- extend base layout -->
{% extends "layout.html" %}

{% block body %}
	{% macro render_field(field, placeholder=None) %}
		{% if field.errors %}
		<div>
		{% elif field.flags.error %}
		<div>
		{% else %}
		<div>
		{% endif %}

		{% set css_class = 'form-control ' + kwargs.pop('class', '') %}
		{{ field(class=css_class, placeholder=placeholder, **kwargs) }}
		</div>
	{% endmacro %}

	{% macro render_checkbox_field(field, text=None) -%}
		<div class="checkbox">
			<label>
				{{ field(type='checkbox', **kwargs) }} {{ text|safe }}
			</label>
		</div>
	{%- endmacro %}

	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?language=pl?key=AIzaSyD9ryFHC07cVPEgeKlRG-wFHRgF9dTPPL8"></script>
	<!-- <script>
		if (navigator.geolocation) {
			success = function(position) {
				var pos = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);

				var date = new Date();
        		date.setTime(date.getTime() + (7*24*60*60*1000));

				document.cookie="latitude=" + pos.lat() + "; expires=" + date.toGMTString() + "; path=/";
				document.cookie="longitude=" + pos.lng() + "; expires=" + date.toGMTString() + "; path=/";
			};
			error = function() {}

			navigator.geolocation.getCurrentPosition(success, error);
		}
	</script> -->

	<div class="auth-box">
		<div class="auth-header">{{ _('Log in') }}</div>
		<div class="auth-content">
			<div class="auth-social">
				<a href="{{ url_for('users.oauth_authorize', provider='facebook') }}" class="btn btn-block btn-sm btn-social btn-facebook">
					<i class="fa fa-facebook"></i>
					{{ _('Log in using Facebook') }}
				</a>
				<!-- <a href="{{ url_for('users.oauth_authorize', provider='twitter') }}" class="btn btn-block btn-sm btn-social btn-twitter">
					<i class="fa fa-twitter"></i>
					Zaloguj się przez Twitter
				</a> -->
			</div>

			<div class="auth-separator">
				{{ _('or') }}
			</div>

			<div class="auth-form">
				<form action="" method="post" name="login">
					{{ form.hidden_tag() }}

					<div class="form-group">
						<div class="input-group">
							<div class="input-group-addon"><i class="fa fa-envelope"></i></div>
							{{ render_field(form.email, placeholder=_('Email')) }}
						</div>
						<div class="form-group has-error">
							<small class="form-group has-error help-block">{{ form.email.errors[0] }}</small>
						</div>
					</div>
					<div class="form-group">
						<div class="input-group">
							<div class="input-group-addon"><i class="fa fa-lock"></i></div>
							{{ render_field(form.password, placeholder=_('Password')) }}
						</div>
						<div class="form-group has-error">
							<small class="help-block">{{ form.password.errors[0] }}</small>
						</div>
					</div>

					<div class="form-group">
						{{ render_checkbox_field(form.remember_me, text=_('Remember me')) }}
					</div>

					<div class="form-group">
						<button type="submit" class="btn btn-success">{{ _('Log in into Adventure') }}</button>
					</div>
				</form>
			</div>

			<div class="auth-footer">
				{{ _('New in Adventures?') }} <a href="/users/register/">{{ _('Register now') }}</a>
				<br><br>
				<a href="/users/lost/">{{ _('Forgot your password?') }}</a>
			</div>
		</div>
	</div>
{% endblock %}

app/templates/users/lost.html
<!-- extend base layout -->
{% extends "layout.html" %}

{% block body %}
	{% macro render_field(field, placeholder=None) %}
		{% if field.errors %}
		<div>
		{% elif field.flags.error %}
		<div>
		{% else %}
		<div>
		{% endif %}

		{% set css_class = 'form-control ' + kwargs.pop('class', '') %}
		{{ field(class=css_class, placeholder=placeholder, **kwargs) }}
		</div>
	{% endmacro %}

	<h2>{{ _('Lost password') }}</h2>
	<br>

	<form action="" method="post" name="lost">
		{{ form.hidden_tag() }}

        <div class="form-group">
			<div class="input-group">
				<div class="input-group-addon"><i class="fa fa-envelope"></i></div>
				{{ render_field(form.email, placeholder=_('Email')) }}
			</div>
			<div class="form-group has-error">
				<small class="form-group has-error help-block">{{ form.email.errors[0] }}</small>
			</div>
		</div>

		<div class="form-group">
			<button type="submit" class="btn btn-success">{{ _('Submit') }}</button>
		</div>
	</form>
{% endblock %}

app/templates/users/lost_email.html
<p>Forgot password?</p>
<p>No problem!</p>
<p>Reset your password here: <a href="{{ confirm_url|safe }}">{{ confirm_url|safe }}</a></p>
<br>
<p>Cheers!</p>

app/templates/users/register.html
<!-- extend base layout -->
{% extends "layout.html" %}

{% block body %}
	{% macro render_field(field, placeholder=None) %}
		{% if field.errors %}
		<div>
		{% elif field.flags.error %}
		<div>
		{% else %}
		<div>
		{% endif %}

		{% set css_class = 'form-control ' + kwargs.pop('class', '') %}
		{{ field(class=css_class, placeholder=placeholder, **kwargs) }}
		</div>
	{% endmacro %}

	<div class="auth-box">
		<div class="auth-header">{{ _('Join to Adventure') }}</div>
		<div class="auth-content">
			<div class="auth-form">
				<form action="" method="post" name="register">
					{{ form.hidden_tag() }}

					<div class="form-group">
						<div class="input-group">
							<div class="input-group-addon"><i class="fa fa-user"></i></div>
							{{ render_field(form.username, placeholder=_('Username'), autofocus="") }}
						</div>
						<div class="form-group has-error">
							<small class="form-group has-error help-block">{{ form.username.errors[0] }}</small>
						</div>
					</div>

					<div class="form-group">
						<div class="input-group">
							<div class="input-group-addon"><i class="fa fa-envelope"></i></div>
							{{ render_field(form.email, placeholder=_('Email')) }}
						</div>
						<div class="form-group has-error">
							<small class="form-group has-error help-block">{{ form.email.errors[0] }}</small>
						</div>
					</div>

					<div class="form-group">
						<div class="input-group">
							<div class="input-group-addon"><i class="fa fa-lock"></i></div>
							{{ render_field(form.password, placeholder=_('Password')) }}
						</div>
						<div class="form-group has-error">
							<small class="form-group has-error help-block">{{ form.password.errors[0] }}</small>
						</div>
					</div>

					<div class="form-group">
						<div class="input-group">
							<div class="input-group-addon"><i class="fa fa-lock"></i></div>
							{{ render_field(form.confirm, placeholder=_('Repeat password')) }}
						</div>
						<div class="form-group has-error">
							<small class="form-group has-error help-block">{{ form.confirm.errors[0] }}</small>
						</div>
					</div>

					<div class="form-group">
						<button type="submit" class="btn btn-success">{{ _('Register to Adventure') }}</button>
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}