app/users/views.py
# -*- coding: utf-8 -*-

from datetime import datetime
from werkzeug import check_password_hash, generate_password_hash
from flask import Blueprint, request, render_template, flash, redirect, url_for
from flask_login import current_user, login_user, logout_user, login_required
from flask_sqlalchemy import get_debug_queries
from flask_babel import gettext

from app import app, db
from app.users.models import User
from app.users.forms import RegisterForm, LoginForm, AccountForm, LostForm, ChangePasswordForm

from app.miscellaneous import not_login_required
from app.token import generate_confirmation_token, confirm_token, generate_lost_password_token
from app.email import send_email

from app.oauth import OAuthSignIn

mod = Blueprint('users', __name__, url_prefix='/users')

# check for slow quieries
@mod.after_request
def after_request(response):
    for query in get_debug_queries():
        if query.duration >= app.config['DATABASE_QUERY_TIMEOUT']:
            app.logger.warning(
                "SLOW QUERY: %s\nParameters: %s\nDuration: %fs\nContext: %s\n" %
                (query.statement, query.parameters, query.duration, query.context)
            )
    return response

# Login
@mod.route('/login/', methods=['GET', 'POST'])
@not_login_required
def login():
    """Handels user login"""

    # get form
    form = LoginForm(request.form)

    if request.method == 'GET':
        return render_template('users/login.html', form=form)

    # verify the login form
    if form.validate_on_submit():
        registered_user = User.query.filter_by(email=form.email.data).first()

        if ((registered_user is not None)
                and check_password_hash(registered_user.password, form.password.data)):
            # login user to system
            login_user(registered_user, remember=form.remember_me.data)
            registered_user.update_login_info()

            return redirect(request.args.get('next') or url_for('simple_page.index'))

        flash(gettext(u'Incorrect email or password'), 'danger')

    return render_template('users/login.html', form=form)

# Register
@mod.route('/register/', methods=['GET', 'POST'])
@not_login_required
def register():
    """Provides registering for user"""

    # if register form is submitted
    form = RegisterForm(request.form)

    # verify the register form
    if form.validate_on_submit():
        # create user and add to database
        user = User(
            username=form.username.data,
            password=generate_password_hash(form.password.data),
            email=form.email.data
        )
        db.session.add(user)
        db.session.commit()

        # sending email
        token = generate_confirmation_token(user.email)
        confirm_url = url_for('users.confirm_email', token=token, _external=True)
        html = render_template('users/activate.html', confirm_url=confirm_url)
        subject = gettext(u"Please confirm your email")
        send_email(user.email, subject, html)

        #login_user(user)

        # everything okay so far
        flash(gettext(u'Confirmation email has been sent'), 'info')
        return redirect(url_for('users.login'))

    return render_template('users/register.html', form=form)

# Logout
@mod.route('/logout/')
@login_required
def logout():
    """Logout user from the system"""

    # logout user from system
    logout_user()

    # everything okay so back
    return redirect(url_for('simple_page.index'))

# Account
@mod.route('/account/', methods=['GET', 'POST'])
@login_required
def account():
    """Show users informations"""

    # get form
    form = AccountForm(request.form, obj=current_user)

    # verify the register form
    if form.validate_on_submit():
        new_email = str(form.email.data)

        if str(current_user.email) != new_email:
            # reset confirmation status
            current_user.confirmed = False
            current_user.confirmed_on = None

            # resending email
            token = generate_confirmation_token(new_email)
            confirm_url = url_for('users.confirm_email', token=token, _external=True)
            html = render_template('users/activate.html', confirm_url=confirm_url)
            subject = gettext(u'Confirm your account - Adventure')
            send_email(new_email, subject, html)
            flash(gettext(u'Confirmation email has been sent'), 'info')

        # if password has not changed we set it to previous
        if ((form.password.data is None) or (not form.password.data)):
            form.password.data = current_user.password
        else: # generate normal password
            form.password.data = generate_password_hash(form.password.data)

        # update user
        form.populate_obj(current_user)

        # update user in database
        db.session.commit()

        # everything is okay
        flash(gettext(u'The changes have been saved'), 'success')
        return redirect(url_for('users.account'))

    return render_template('users/account.html', form=form)

# Lost password
@mod.route('/lost/', methods=['GET', 'POST'])
@not_login_required
def lost():
    """Allow for user to get lost password"""

    # get form
    form = LostForm(request.form)

    # verify the register form
    if form.validate_on_submit():
        token = generate_lost_password_token(form.email.data)
        confirm_url = url_for('users.change_password', token=token, _external=True)
        html = render_template('users/lost_email.html', confirm_url=confirm_url)
        subject = gettext(u'New password request - Adventure')
        send_email(form.email.data, subject, html)
        flash(gettext(u'Follow the instructions in sent email'), 'info')

        return redirect(url_for('simple_page.index'))

    return render_template('users/lost.html', form=form)

# Login authorization
@mod.route('/authorize/<provider>')
def oauth_authorize(provider):
    if not current_user.is_anonymous():
        return redirect(url_for('simple_page.index'))

    oauth = OAuthSignIn.get_provider(provider)
    return oauth.authorize()

# Sign in callback
@mod.route('/callback/<provider>')
def oauth_callback(provider):
    if not current_user.is_anonymous():
        return redirect(url_for('simple_page.index'))

    oauth = OAuthSignIn.get_provider(provider)
    social_id, username, email = oauth.callback()
    if social_id is None:
        flash(getttext(u'Authentication failed'), 'danger')
        return redirect(url_for('simple_page.index'))

    # check if user exists and if no creates new
    user = User.query.filter_by(social_id=social_id).first()
    if user is None:
        user = User(
            username=username,
            password='',
            email=email,
            social_id=social_id
        )
        db.session.add(user)
        db.session.commit()

    login_user(user, remember=True)
    user.update_login_info()
    return redirect(url_for('simple_page.index'))

# Send confirmation email
@mod.route('/confirmation/')
@login_required
def resend_confirmation_email():
    # resending email
    token = generate_confirmation_token(current_user.email)
    confirm_url = url_for('users.confirm_email', token=token, _external=True)
    html = render_template('users/activate.html', confirm_url=confirm_url)
    subject = gettext(u'Please confirm your email')
    send_email(current_user.email, subject, html)

    flash(gettext(u'Confirmation email has been sent'), 'info')
    return redirect(url_for('users.account'))

# Confirm email
@mod.route('/confirm/<token>', methods=['GET', 'POST'])
@login_required
def confirm_email(token):
    try:
        email = confirm_token(token)
    except:
        flash(gettext(u'The confirmation link is invalid or has expired'), 'warning')

    # check if user with decoded email exists
    user = User.query.filter_by(email=email).first_or_404()
    if user.confirmed:
        flash(gettext(u'Account already confirmed'), 'info')
        return redirect(url_for('simple_page.index'))

    # update user informations and add to database
    user.confirmed = True
    user.confirmed_on = datetime.now()
    db.session.add(user)
    db.session.commit()

    flash(gettext(u'You have confirmed your account. Enjoy'), 'success')
    return redirect(url_for('simple_page.index'))

# Change lost password
@mod.route('/lost/<token>', methods=['GET', 'POST'])
def change_password(token):
    try:
        email = confirm_token(token)
    except:
        flash(gettext(u'The confirmation link is invalid or has expired'), 'warning')

    # check if user with decoded email exists
    user = User.query.filter_by(email=email).first_or_404()

    form = ChangePasswordForm(request.form, obj=user)

    if form.validate_on_submit():
        # update user
        form.password.data = generate_password_hash(form.password.data)
        form.populate_obj(user)

        # update user in database
        db.session.commit()

        # everything is okay
        flash(gettext(u'Your password has been successfully changed'), 'success')
        return redirect(url_for('users.login'))

    return render_template('users/change_password.html', form=form)

app/views.py
# -*- coding: utf-8 -*-

from flask import Blueprint, request, render_template
from flask import flash, redirect, url_for, jsonify

from flask_login import current_user
from flask_babel import gettext
from app.adventures.models import Adventure, Coordinate, AdventureParticipant
from app.adventures import constants as ADVENTURES
from app.miscellaneous import get_current_user_id
from app.recommender_system import get_recommended_adventures
from app.users.models import User
from app import app, cache, db, celery

from app.mine.forms import ReportForm
from app.mine.models import UserReports

mod = Blueprint('simple_page', __name__, template_folder='templates')

@celery.task(bind=True)
def get_all_adventures(self, user_id, position):
    all_adventures = {
        'most_recent': [],
        'start_soon': [],
        'top_adventures': []
    }

    recommended_adventures = get_recommended_adventures(user_id=user_id,
                                                        user_position=position)

    for sort_type, adventures in recommended_adventures.items():
        for adventure in adventures:
            # get creator of the event and check if still exists
            user = User.query.filter_by(id=adventure.creator_id).first()
            if user is None:
                continue

            # get joined participants
            participants = adventure.get_participants()

            action = 'no-action'
            if user_id:
                participant = AdventureParticipant.query.filter_by(
                    adventure_id=adventure.id,
                    user_id=user_id
                ).first()

                if (participant is None) or (not participant.is_active()):
                    action = 'join'
                else:
                    action = 'leave'

                if adventure.creator_id == user_id:
                    action = 'manage'

            coordinates = Coordinate.query.filter_by(
                adventure_id=adventure.id
            ).all()

            markers = [(coordinate.latitude, coordinate.longitude)
                       for coordinate in coordinates]

            all_adventures[sort_type].append({
                'id': adventure.id,
                'username': user.username,
                'date': adventure.date.strftime('%d.%m.%Y %H:%M'),
                'info': adventure.info,
                'joined': len(participants),
                'mode': ADVENTURES.MODES[int(adventure.mode)],
                'action': action,
                'markers': markers
            })

        self.update_state(state='PROGRESS',
                          meta={'most_recent': all_adventures['most_recent'],
                                'start_soon': all_adventures['start_soon'],
                                'top_adventures': all_adventures['top_adventures']})

    return {
        'status': 'COMPLETED',
        'most_recent': all_adventures['most_recent'],
        'start_soon': all_adventures['start_soon'],
        'top_adventures': all_adventures['top_adventures']
    }

@mod.route('/status/<task_id>')
def taskstatus(task_id):
    task = get_all_adventures.AsyncResult(task_id)

    if task.state == 'PENDING':
        # job did not start yet
        response = {
            'state': task.state,
            'most_recent': [],
            'start_soon': [],
            'top_adventures': []
        }
    elif task.state != 'FAILURE':
        response = {
            'state': task.state,
            'most_recent': task.info.get('most_recent', []),
            'start_soon': task.info.get('start_soon', []),
            'top_adventures': task.info.get('top_adventures', [])
        }
    else:
        # something went wrong in the background job
        response = {
            'state': task.state,
            'most_recent': [],
            'start_soon': [],
            'top_adventures': [],
            'status': str(task.info),  # this is the exception raised
        }

    return jsonify(response)

#@cache.cached(timeout=5)
def show_all_adventures():
    position = {
        'latitude': request.cookies.get('latitude'),
        'longitude': request.cookies.get('longitude')
    }

    user_id = get_current_user_id()
    task = get_all_adventures.apply_async(args=(user_id, position))

    return render_template(
        'all.html',
        task_id=task.id
    )

# Index - main path
@mod.route("/")
def index():
    if not current_user.is_authenticated():
        return render_template('landing.html')

    return show_all_adventures()

# Show all adventures (if not logged in)
@mod.route("/all/")
def show_adventures():
    return show_all_adventures()

# About us
@mod.route("/about")
def about():
    return render_template('about.html')

# Contact
@mod.route("/contact/", methods=['GET', 'POST'])
def contact():

    form = ReportForm(request.form)

    if current_user.is_authenticated():
        form = ReportForm(request.form, obj=current_user)

    if form.validate_on_submit():
        user_id = None
        if current_user.is_authenticated():
            user_id = current_user.id

        report = UserReports(
            user_id=user_id,
            email=form.email.data,
            subject=form.subject.data,
            message=form.message.data
        )

        db.session.add(report)
        db.session.commit()

        flash(gettext(u'Message sent. Thank you for contact. \
                        We really appreciate it!'),
              'success')
        return redirect(url_for('simple_page.index'))

    return render_template(
        'contact.html',
        form=form
    )

# How it works
@mod.route("/how-it-works")
def how_it_works():
    return render_template('how-it-works.html')

# Features in our app
@mod.route("/features")
def features():
    return render_template('features.html')

# Carrers - avaiable
@mod.route("/carrers")
def carrers():
    return render_template('carrers.html')

# Support
@mod.route("/support")
def support():
    return render_template('support.html')

app/templates/all.html
<!-- extend base layout -->
{% extends "layout.html" %}
{% block body %}
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?language=pl?key=AIzaSyD9ryFHC07cVPEgeKlRG-wFHRgF9dTPPL8"></script>

	<!-- Activity indicator -->
	<script src="/static/js/spin.js"></script>
	<script>
		var mostRecent = [];
		var stortSoon = [];
		var topAdvenutres = [];
		var spinner = new Spinner({radius: 14, length: 12, width: 6, lines: 12});

		function resetActive() {
			$('button').each(function(index, element) {
				$(this).removeClass("active")
			});
		}

		function showMostRecent(button) {
			// reset active buttons
			resetActive();

			// change button to active
			$(button).addClass("active")
			show(mostRecent)
		}

		function showStartSoon(button) {
			// reset active buttons
			resetActive();

			// change button to active
			$(button).addClass("active")
			show(startSoon)
		}

		function showTopAdventures(button) {
			// reset active buttons
			resetActive();

			// change button to active
			$(button).addClass("active")
			show(topAdvenutres)
		}

		function updateMostRecent(button, newMostRecent) {
			resetActive();

			// change button to active
			$(button).addClass("active");

			var toUpdate = [];
			for (var i = 0; i < newMostRecent.length; i++) {
				var isNew = true;
				for (var j = 0; j < mostRecent.length; j++) {
					if (newMostRecent[i].id === mostRecent[j].id) {
						isNew = false;
						break;
					}
				}

				if (isNew) {
					mostRecent.push(newMostRecent[i]);
					toUpdate.push(newMostRecent[i]);
				}
			}

			show(toUpdate, "update");
		}

		function show(adventures) {
			$("#adventures").empty();

			for (var i = 0; i < adventures.length; i++) {
				var adventureRow = '' +
				'<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-4">' +
					'<div class="adventure-box">' +
						'<div class="adventure-image" style="background-image:url(\'';

				var image_url = 'https://maps.googleapis.com/maps/api/staticmap?size=640x640&style=feature:road|element:all|visibility:on&style=feature:road|element:labels.icon|visibility:off&style=feature:road|element:labels.text.fill|color:0x959595&style=feature:poi|element:all|visibility:off&style=feature:administrative|element:all|visiblity:off&path=color:0x0000ff|weight:5'
				for (var j = 0; j < adventures[i].markers.length; j++) {
					image_url += '|' + adventures[i].markers[j][0] + ',' + adventures[i].markers[j][1]
				}

				action = '';
				if (adventures[i].action == 'no-action')
					action = 'No action';
				else if (adventures[i].action == 'join') {
					action = '<a href="/adventures/join/' + adventures[i].id + '">{{ _("Join") }}</a>';
				} else if (adventures[i].action == 'leave') {
					action = '<a href="/adventures/leave/' + adventures[i].id + '">{{ _("Leave") }}</a>';
				} else if (adventures[i].action == 'manage') {
					action = '<a href="/adventures/edit/' + adventures[i].id + '">{{ _("Edit") }}</a> | <a href="/adventures/delete/' + adventures[i].id + '" onclick="return confirm(\'{{ _("Are you sure you want to delete this Adventure?") }}\');">{{ _("Delete") }}</a>';
				}

				adventureRow += image_url;
				adventureRow += '\');">' +
							'<a href="/adventures/' + adventures[i].id + '" class="permacover"></a>' +
							'<div href="/adventures/' + adventures[i].id + '" class="adventure-header-author">' + adventures[i].username + '</div>' +
						'</div><!-- /.object-header -->' +
						'<div class="adventure-meta">' +
							'<div class="adventure-title">' +
								'<a href="/adventures/' + adventures[i].id + '">' + adventures[i].info + '</a>' +
							'</div>' +
							'<div class="adventure-details clearfix">' +
								'<div class="left"><i class="fa fa-user"></i> ' + adventures[i].joined + '</div>' +
								'<div class="right"><i class="fa fa-bicycle"></i> ' + adventures[i].mode + '</div>' +
								'<div style="clear:both"></div>' +
								'<div class="left"><i class="fa fa-clock-o"></i> ' + adventures[i].date + '</div>' +
								'<div class="right"><i class="fa fa-gear"></i> ';
									adventureRow += action;
				adventureRow += '' +
								'</div>' +
							'</div>' +
						'</div>' +
					'</div>' +
				'</div>';

				$("#adventures").append(adventureRow);
			}
		}

		function update_progress(status_url) {
			// send GET request to status URL
			$.getJSON(status_url, function(data) {
				mostRecent = data['most_recent'];
				startSoon = data['start_soon'];
				topAdvenutres = data['top_adventures'];
				// updateMostRecent($("#most_recent").get(), data['most_recent']);

				if (data['state'] != 'PENDING' && data['state'] != 'PROGRESS') {
					// show adventures
					showMostRecent($("#most_recent").get());

					if (mostRecent.length <= 0) {
						$("#no-adventure").show(); // show no adventures comment
					} else {
						$("#all-adventures").show(); // show all adventures
					}

					// stop spinner with small delay
					setTimeout(function() {
						spinner.stop();
					}, 500);
				} else {
					// rerun in 200 miliseconds
					setTimeout(function() {
						update_progress(status_url);
					}, 200);
				}
			});
		}

		$(window).load(function() {
			// activate spinner
			spinner.spin(document.getElementById('spinner'));

			// get tasks
			update_progress('/status/{{ task_id }}');
		});
	</script>

	<div id="spinner"></div>

	<div id="no-adventure" class="row text-center" style="display: none">
		<div class="col-sm-8 col-sm-offset-2">
			<p class="lead">
				{{ _('There is not active Adventures <i class="fa fa-frown-o"></i><br> Be first and create yours')}}
			</p>
			<p><a class="hd-btn hd-btn-black" href="{{ url_for('adventures.new') }}">{{ _('Create Adventure') }}</a></p>
		</div>
	</div>

	<div id="all-adventures" style="display: none">
		<div class="text-center">
			<div class="btn-group" role="group" aria-label="adventure feed">
				<button id="most_recent" type="button" class="btn btn-info" onclick="showMostRecent(this)">{{ _('Most Recent') }}</button>
				<button id="start_soon" type="button" class="btn btn-info" onclick="showStartSoon(this)">{{ _('Start Soon') }}</button>
				<button id="top_adventures" type="button" class="btn btn-info" onclick="showTopAdventures(this)">{{ _('Top Adventures') }}</button>
			</div>
		</div>
		<br><br><br>
		<div id="adventures" class="row"></div>
	</div>
{% endblock %}

app/templates/contact.html
{% extends "layout.html" %}
{% block body %}
    {% macro render_field(field, placeholder=None) %}
        {% if field.errors %}
        <div>
        {% elif field.flags.error %}
        <div>
        {% else %}
        <div>
        {% endif %}

        {% set css_class = 'form-control ' + kwargs.pop('class', '') %}
        {{ field(class=css_class, placeholder=placeholder, **kwargs) }}
        </div>
    {% endmacro %}

    <div class="contact-box">
        <div class="contact-title">{{ _('Contact') }}</div>
        <div class="contact-subtitle">
            {{ _('If') }}:
            <ul>
                <li>{{ _('you have an idea how we can improve site?') }}</li>
                <li>{{ _('you have found a bug?') }}</li>
                <li>{{ _('you have a question?') }}</li>
            </ul>
            {{ _('Do not hesitate and leave message!')}}
        </div>
        <div class="contact-content">
            <div class="contact-form">
                <form action="" method="post" name="contact">
                    {{ form.hidden_tag() }}

                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon"><i class="fa fa-envelope"></i></div>
                            {{ render_field(form.email, placeholder=_('Email (optional)')) }}
                        </div>
                        <div class="form-group has-error">
                            <small class="form-group has-error help-block">{{ form.email.errors[0] }}</small>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon"><i class="fa fa-edit"></i></div>
                            {{ render_field(form.subject, placeholder=_('Subject (optional)')) }}
                        </div>
                        <div class="form-group has-error">
                            <small class="form-group has-error help-block">{{ form.subject.errors[0] }}</small>
                        </div>
                    </div>

                    <div class="form-group">
                        {{ render_field(form.message, placeholder=_('What do you want to share with us?'), rows="6", style="max-width: 100%") }}
                        <div class="form-group has-error">
                            <small class="form-group has-error help-block">{{ form.message.errors[0] }}</small>
                        </div>
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-success">{{ _('Send message') }}</button>
                    </div>
                </form>
            </div>
            <div class="contact-footer">{{ _('We are grateful for every message and commen!t') }}</div>
        </div>
    </div>
{% endblock %}

app/templates/flash.html
{% with messages = get_flashed_messages(with_categories=true) %}
	{% if messages %}
		{% for category, message in messages %}
			<div class="alert alert-{{ category }}">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				{{ message }}
			</div>
		{% endfor %}
	{% endif %}
{% endwith %}

app/templates/landing.html
<!-- extend base layout -->
{% extends "layout.html" %}

{% set story=True %}
{% block story %}
	<section id="intro">
		<div class="text text-center">
			<div class="row">
				<div class="col-sm-8 col-sm-offset-2">
					<p class="lead">
						{{ _('Do you ride for fun, or you make your path a challange?<br>Find friends, company and go on Adventure!')}}
					</p>
					<p><a class="hd-btn hd-btn-black" href="{{ url_for('users.register') }}">{{ _('Register now') }}</a></p>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

app/templates/layout.html
<!doctype html>
<head>
	<title>{{ _('Adventure') }}</title>

	<meta name="description" content="{{ _('Adventure is a site which connects bikers and helps them to go on adventures.')}}"/>
	<meta name="viewport" content="initial-scale=1.0, user-scalable=no"/>
	<meta charset="utf-8" />
	<meta keywords="adventure, przygoda, rowery, wyruszać, rower, razem, jechać, uczestnicy" />
	<meta http-equiv="content-language" content="pl" />
	<meta name="robots" content="index, follow">

	<style>
		body {
			padding-top: 60px;
			padding-bottom: 100px;
		}
	</style>

	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

	<script type="text/javascript" src="//code.jquery.com/jquery-2.1.1.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js"></script>

	<!-- Style css -->
	<link href="/static/css/style.css" rel="stylesheet">

	<!-- Bootstrap -->
	<link href="/static/css/bootstrap.css" rel="stylesheet">
	<link href="/static/css/bootstrap-social.css" rel="stylesheet">
	<script src="/static/js/bootstrap.min.js"></script>

	<!-- Bootstrap DatePicker -->
	<link href="//cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/a549aa8780dbda16f6cff545aeabc3d71073911e/build/css/bootstrap-datetimepicker.css" rel="stylesheet">
	<script src="//cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/a549aa8780dbda16f6cff545aeabc3d71073911e/src/js/bootstrap-datetimepicker.js"></script>

	<!-- Bootstrap Select -->
	<link href="/static/css/bootstrap-select.min.css" rel="stylesheet">
	<script src="/static/js/bootstrap-select.min.js"></script>
	<script src="/static/js/i18n/defaults-pl_PL.js"></script>

	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-65280522-1', 'auto');
	  ga('send', 'pageview');
	</script>
	<script>(function(d, s, id) {
	var js, fjs = d.getElementsByTagName(s)[0];
	if (d.getElementById(id)) return;
	js = d.createElement(s); js.id = id;
	js.src = "//connect.facebook.net/pl_PL/sdk.js#xfbml=1&version=v2.3&appId=1591505724433841";
	fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
</head>
<body>
	<div id="fb-root"></div>

	<div class="navbar navbar-default navbar-fixed-top" role="navigation" style="padding-bottom: 0px; margin-bottom: 0px;">
		<div class="container">
			<div class="row">
				<div class="navbar-header">
					<a class="navbar-brand" href="/"><i class="fa fa-bicycle"></i> {{ _('Adventure') }}</a>
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="fa fa-bars fa-inverse fa-2x"></span>
						<span class="sr-only">Toggle navigation</span>
					</button>
				</div>
				<div class="collapse navbar-collapse">
				     <ul class="nav navbar-nav navbar-right">
						{% if g.user.is_authenticated() %}
					        <li><a href="{{ url_for('users.account') }}">{{ _('Account') }}</a></li>
					        <li><a href="{{ url_for('users.logout') }}">{{ _('Logout') }}</a></li>
					        <li><a href="{{ url_for('adventures.new') }}">{{ _('Create Adventure') }}</a></li>
					        <li><a href="{{ url_for('adventures.my_adventures') }}">{{ _('My Adventures') }}</a></li>
						{% else %}
							<li><a href="{{ url_for('simple_page.show_adventures') }}">{{ _('Adventures')}}</a>
							<li><a href="{{ url_for('users.login') }}">{{ _('Login') }}</a></li>
							<li><a href="{{ url_for('users.register') }}">{{ _('Register') }}</a></li>
						{% endif %}
						<li><a href="{{ url_for('adventures.search') }}">
							<i class="fa fa-search" style="padding-right: 10px;"></i>{{ _('Search for Adventures') }}
						</a></li>
				    </ul>
				</div>
			</div>
		</div>
	</div>

	{% block story %}
	{% endblock story %}

	{% if (g.user.is_authenticated() and g.user.is_admin()) %}
		{% include "admin/panel.html" %}
	{% endif %}

	{% if (story is not defined) or (not story) %}
		<section id="main">
			<div class="container">
				{% include "flash.html" %}

				{% block body %}
				{% endblock %}
			</div>
		</section>
	{% endif %}

	<section id="footer" class="text-center">
		<div class="container">
			<div class="row">
				<div class="col-md-4 col-sm-6"><a href="#">{{ _('Blog') }}</a></div>
				<div class="col-md-4 col-sm-6"><a href="{{ url_for('simple_page.contact') }}"><b>{{ _('Contact') }}</b></a></div>
				<div class="col-md-4 col-sm-6"><a href="#">{{ _('About') }}</a></div>
				<div class="col-md-4 col-sm-6"><a href="#">{{ _('Features') }}</a></div>
				<div class="col-md-4 col-sm-6"><a href="#">{{ _('Privacy') }}</a></div>
				<div class="col-md-4 col-sm-6"><a href="#">{{ _('Help') }}</a></div>
			</div>

			<div class="row social">
				<div class="col-md-6 col-sm-6 col-xs-6"><a href="https://www.facebook.com/przygodapl"><i class="fa fa-facebook fa-2x"></i></a></div>
				<div class="col-md-6 col-sm-6 col-xs-6"><a href="#footer"><i class="fa fa-twitter fa-2x"></i></a></div>
			</div>

			<div class="copyrights text-center">
				<i class="fa fa-copyright"></i> 2015 Przygoda. All Rights Reserved.
			</div>
		</div>
	</section>
</body>